export enum ERROR_CODE {
    UNEXPECTED = 'E_UNEXPECTED',
    METHOD_NOT_IMPLEMENTED = 'E_METHOD_NOT_IMPLEMENTED',
    EVENT_NOT_IMPLEMENTED = 'E_EVENT_NOT_IMPLEMENTED',
    VALIDATION_ERROR = 'E_VALIDATION_ERROR',
    METHOD_IS_TIMED_OUT = 'E_METHOD_IS_TIMED_OUT',
    CANCELLED = 'E_CANCELLED',
}
